// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPL.Attendance.Data.Context;

#nullable disable

namespace SPL.Attendance.Data.Migrations
{
    [DbContext(typeof(SPLAttendanceDbContext))]
    partial class SPLAttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SPL.Attendance.Data.Entities.Attendance", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("AttendanceDate").HasColumnType("date");
                b.Property<DateTime?>("CheckInTime").HasColumnType("datetime(6)");
                b.Property<DateTime?>("CheckOutTime").HasColumnType("datetime(6)");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<string>("Status").HasMaxLength(20).HasColumnType("varchar(20)");
                b.Property<decimal?>("WorkHours").HasColumnType("decimal(5,2)");
                b.HasKey("Id");
                b.HasIndex(new[] { "EmployeeId", "AttendanceDate" }, "UX_Attendance_Employee_Date").IsUnique();
                b.ToTable("Attendances");
            });

            modelBuilder.Entity("SPL.Attendance.Data.Entities.Employee", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Email").HasMaxLength(150).HasColumnType("varchar(150)");
                b.Property<string>("EmployeeCode").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<bool>("IsActive").HasColumnType("tinyint(1)");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<int?>("SupervisorId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("EmployeeCode").IsUnique();
                b.HasIndex("SupervisorId");
                b.ToTable("Employees");
                b.HasData(new { Id = 1, EmployeeCode = "EMP001", Name = "Demo Employee",
                                Email = "demo@spl.com", IsActive = true });
            });

            modelBuilder.Entity("SPL.Attendance.Data.Entities.Attendance", b =>
            {
                b.HasOne("SPL.Attendance.Data.Entities.Employee", "Employee")
                 .WithMany("Attendances")
                 .HasForeignKey("EmployeeId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
                b.Navigation("Employee");
            });

            modelBuilder.Entity("SPL.Attendance.Data.Entities.Employee", b =>
            {
                b.HasOne("SPL.Attendance.Data.Entities.Employee", "Supervisor")
                 .WithMany()
                 .HasForeignKey("SupervisorId")
                 .OnDelete(DeleteBehavior.Restrict);
                b.Navigation("Supervisor");
                b.Navigation("Attendances");
            });
#pragma warning restore 612, 618
        }
    }
}
